-- Passo 1: Adicionar coluna game_n em live_scores (rodar uma vez)
ALTER TABLE live_scores ADD COLUMN IF NOT EXISTS game_n INTEGER;

-- Passo 2: Popular game_n nos registros existentes de jogos de grupo
UPDATE live_scores SET game_n = CASE game_key
  WHEN 'MEX_RSA' THEN 1
  WHEN 'KOR_CZE' THEN 2
  WHEN 'CAN_BIH' THEN 3
  WHEN 'USA_PAR' THEN 4
  WHEN 'QAT_SUI' THEN 5
  WHEN 'BRA_MAR' THEN 6
  WHEN 'HAI_SCO' THEN 7
  WHEN 'AUS_TUR' THEN 8
  WHEN 'GER_CUW' THEN 9
  WHEN 'NED_JPN' THEN 10
  WHEN 'CIV_ECU' THEN 11
  WHEN 'SWE_TUN' THEN 12
  WHEN 'ESP_CPV' THEN 13
  WHEN 'BEL_EGY' THEN 14
  WHEN 'KSA_URU' THEN 15
  WHEN 'IRN_NZL' THEN 16
  WHEN 'ARG_ALG' THEN 17
  WHEN 'FRA_SEN' THEN 18
  WHEN 'IRQ_NOR' THEN 19
  WHEN 'AUT_JOR' THEN 20
  WHEN 'POR_COD' THEN 21
  WHEN 'ENG_CRO' THEN 22
  WHEN 'GHA_PAN' THEN 23
  WHEN 'UZB_COL' THEN 24
  WHEN 'CZE_RSA' THEN 25
  WHEN 'SUI_BIH' THEN 26
  WHEN 'CAN_QAT' THEN 27
  WHEN 'MEX_KOR' THEN 28
  WHEN 'TUR_PAR' THEN 29
  WHEN 'USA_AUS' THEN 30
  WHEN 'SCO_MAR' THEN 31
  WHEN 'BRA_HAI' THEN 32
  WHEN 'NED_SWE' THEN 33
  WHEN 'GER_CIV' THEN 34
  WHEN 'ECU_CUW' THEN 35
  WHEN 'TUN_JPN' THEN 36
  WHEN 'ESP_KSA' THEN 37
  WHEN 'BEL_IRN' THEN 38
  WHEN 'URU_CPV' THEN 39
  WHEN 'NZL_EGY' THEN 40
  WHEN 'ARG_AUT' THEN 41
  WHEN 'FRA_IRQ' THEN 42
  WHEN 'NOR_SEN' THEN 43
  WHEN 'JOR_ALG' THEN 44
  WHEN 'POR_UZB' THEN 45
  WHEN 'ENG_GHA' THEN 46
  WHEN 'PAN_CRO' THEN 47
  WHEN 'COL_COD' THEN 48
  WHEN 'SUI_CAN' THEN 49
  WHEN 'BIH_QAT' THEN 50
  WHEN 'SCO_BRA' THEN 51
  WHEN 'MAR_HAI' THEN 52
  WHEN 'CZE_MEX' THEN 53
  WHEN 'RSA_KOR' THEN 54
  WHEN 'ECU_GER' THEN 55
  WHEN 'CUW_CIV' THEN 56
  WHEN 'JPN_SWE' THEN 57
  WHEN 'TUN_NED' THEN 58
  WHEN 'TUR_USA' THEN 59
  WHEN 'PAR_AUS' THEN 60
  WHEN 'NOR_FRA' THEN 61
  WHEN 'SEN_IRQ' THEN 62
  WHEN 'CPV_KSA' THEN 63
  WHEN 'URU_ESP' THEN 64
  WHEN 'EGY_IRN' THEN 65
  WHEN 'NZL_BEL' THEN 66
  WHEN 'PAN_ENG' THEN 67
  WHEN 'CRO_GHA' THEN 68
  WHEN 'COL_POR' THEN 69
  WHEN 'COD_UZB' THEN 70
  WHEN 'ALG_AUT' THEN 71
  WHEN 'JOR_ARG' THEN 72
  ELSE NULL
END
WHERE game_n IS NULL;

-- Passo 3: Para jogos KO, use o endpoint PATCH /admin/set-game-n para taggear manualmente.
-- Ex: curl -X PATCH https://<worker>/admin/set-game-n -d '{"adminPass":"...","game_key":"BRA_ARG","game_n":89}'

-- Verificar resultado:
SELECT game_key, game_n, goals_home, goals_away FROM live_scores ORDER BY game_n NULLS LAST;